# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem,QVBoxLayout
import requests
import stockapi
import datetime 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 55, 161, 31))
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(70, 155, 161, 31))
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 160, 691, 271))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")

        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 50, 171, 41))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stock Details"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.pushButton.clicked.connect(self.button_click)
        self.label.setText(_translate("MainWindow", "Enter your Stock Code"))
#         self.lineEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))

    def button_click(self):
        self.update()
        
        stockprice,initialtime=stockapi.get_stock_data(self.lineEdit.text())
        
     #   print(stockprice)
        
        self.create_tables()           
        self.insert_tables(stockprice,initialtime)

    def update(self):
        self.label.adjustSize()
  
    def create_tables(self):
       
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setItem(0,0,QTableWidgetItem("Date/Time"))
        self.tableWidget.setItem(0,1,QTableWidgetItem("Open"))
        self.tableWidget.setItem(0,2,QTableWidgetItem("High"))
        self.tableWidget.setItem(0,3,QTableWidgetItem("Low"))
        self.tableWidget.setItem(0,4,QTableWidgetItem("Close"))
        self.tableWidget.setItem(0,5,QTableWidgetItem("Volume"))
      
    def insert_tables(self,stockprice,initialtime):
        
        i=1
        for key,value in stockprice.items():
           
            self.tableWidget.setItem(i,0,QTableWidgetItem(key))
            self.tableWidget.setItem(i,1,QTableWidgetItem(stockprice[key]['1. open']))
            self.tableWidget.setItem(i,2,QTableWidgetItem(stockprice[key]['2. high']))
            self.tableWidget.setItem(i,3,QTableWidgetItem(stockprice[key]['3. low']))
            self.tableWidget.setItem(i,4,QTableWidgetItem(stockprice[key]['4. close']))
            self.tableWidget.setItem(i,5,QTableWidgetItem(stockprice[key]['5. volume']))
            i+=1
            if i > 10:
                break

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    sys.exit(app.exec_())
